"""
PR comment publisher — posts inline comments and PR-level summaries.
"""
from __future__ import annotations
import logging
from typing import List

from github.PullRequest import PullRequest

from integrations.github.client import get_pull_request
from analysis.rules.base import Finding

logger = logging.getLogger(__name__)

RULE_PREFIX = "⚙️ **Rule Engine**"
AI_PREFIX = "🤖 **AI Review**"


def _format_comment(finding: Finding) -> str:
    prefix = AI_PREFIX if finding.source == "ai" else RULE_PREFIX
    lines = [
        f"{prefix} · `{finding.rule_id}` · **{finding.severity.upper()}**",
        "",
        f"**Issue:** {finding.message}",
    ]
    if finding.suggestion:
        lines += ["", f"**Suggestion:** {finding.suggestion}"]
    lines += [
        "",
        f"*Confidence: {finding.confidence:.0%} · Category: {finding.category}*",
    ]
    return "\n".join(lines)


def publish_findings(
    repo_full_name: str,
    pr_number: int,
    commit_sha: str,
    findings: List[Finding],
) -> List[Finding]:
    """
    Post each finding as an inline PR review comment.
    Returns the list of findings that failed to post inline (due to being unmodified/out-of-diff).
    """
    if not findings:
        return []

    pr: PullRequest = get_pull_request(repo_full_name, pr_number)
    
    commit = None
    try:
        commit = pr.base.repo.get_commit(commit_sha)
    except Exception:
        try:
            commit = pr.base.repo.get_commit(pr.head.sha)
        except Exception as exc:
            logger.warning("Could not resolve commit for SHA %s or head %s: %s", commit_sha, pr.head.sha, exc)

    failed_inline: List[Finding] = []
    posted = 0

    for f in findings:
        body = _format_comment(f)
        posted_inline = False
        if commit:
            try:
                pr.create_review_comment(
                    body=body,
                    commit=commit,
                    path=f.file_path,
                    line=f.line_number,
                    side="RIGHT",
                )
                posted += 1
                posted_inline = True
            except Exception as exc:
                logger.debug("Inline comment failed for %s:%d (%s)", f.file_path, f.line_number, exc)

        if not posted_inline:
            failed_inline.append(f)

    logger.info("Posted %d inline comments. %d findings failed to post inline.", posted, len(failed_inline))
    return failed_inline


def publish_summary(
    repo_full_name: str,
    pr_number: int,
    summary: str,
    risk_score: float,
) -> None:
    """Post a top-level PR summary comment."""
    pr: PullRequest = get_pull_request(repo_full_name, pr_number)
    risk_emoji = "🔴" if risk_score >= 7 else "🟡" if risk_score >= 4 else "🟢"
    body = (
        f"## {risk_emoji} AI Code Review Summary\n\n"
        f"**Risk Score:** {risk_score}/10\n\n"
        f"{summary}\n\n"
        f"---\n"
        f"*Generated by AI Code Review Platform — hybrid rule-based + GPT-3.5 analysis*"
    )
    try:
        pr.create_issue_comment(body)
    except Exception as exc:
        logger.error("Failed to post summary on PR #%d: %s", pr_number, exc)
